# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
name: Mi primer workflow
on:
  push:
    branches: [ master ]
  jobs:
    Mi-primer-job:
      name: Mi primer job
      runs-on: ubuntu-latest
      steps:
       - name: Imprimir 
         env:
           MI_VARIABLE: Hola mundo
         run: |
           echo $MI_VARIABLE.
